//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuTTY_Deployment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PuTTY_Deployment.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Gakuseisean_Aire_Developer {
            get {
                object obj = ResourceManager.GetObject("Gakuseisean_Aire_Developer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\Software\SimonTatham\PuTTY\Sessions\STARPRD]
        ///&quot;Present&quot;=dword:00000001
        ///&quot;HostName&quot;=&quot;STARPRD.GENCO.COM&quot;
        ///&quot;LogFileName&quot;=&quot;putty.log&quot;
        ///&quot;LogType&quot;=dword:00000000
        ///&quot;LogFileClash&quot;=dword:ffffffff
        ///&quot;LogFlush&quot;=dword:00000001
        ///&quot;SSHLogOmitPasswords&quot;=dword:00000001
        ///&quot;SSHLogOmitData&quot;=dword:00000000
        ///&quot;Protocol&quot;=&quot;telnet&quot;
        ///&quot;PortNumber&quot;=dword:000011fa
        ///&quot;CloseOnExit&quot;=dword:00000001
        ///&quot;WarnOnClose&quot;=dword:00000001
        ///&quot;PingInterval&quot;=dword:00000005
        ///&quot;PingIntervalSecs&quot;=dword:0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string STARPRD {
            get {
                return ResourceManager.GetString("STARPRD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\Software\SimonTatham\PuTTY\Sessions\STARQA]
        ///&quot;Present&quot;=dword:00000001
        ///&quot;HostName&quot;=&quot;crptmoqa1app01.genco.com&quot;
        ///&quot;LogFileName&quot;=&quot;putty.log&quot;
        ///&quot;LogType&quot;=dword:00000000
        ///&quot;LogFileClash&quot;=dword:ffffffff
        ///&quot;LogFlush&quot;=dword:00000001
        ///&quot;SSHLogOmitPasswords&quot;=dword:00000001
        ///&quot;SSHLogOmitData&quot;=dword:00000000
        ///&quot;Protocol&quot;=&quot;telnet&quot;
        ///&quot;PortNumber&quot;=dword:00001240
        ///&quot;CloseOnExit&quot;=dword:00000001
        ///&quot;WarnOnClose&quot;=dword:00000001
        ///&quot;PingInterval&quot;=dword:00000005
        ///&quot;PingIntervalSecs&quot;=d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string STARQA {
            get {
                return ResourceManager.GetString("STARQA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\Software\SimonTatham\PuTTY\Sessions\STARSTG]
        ///&quot;Present&quot;=dword:00000001
        ///&quot;HostName&quot;=&quot;starstg.genco.com&quot;
        ///&quot;LogFileName&quot;=&quot;putty.log&quot;
        ///&quot;LogType&quot;=dword:00000000
        ///&quot;LogFileClash&quot;=dword:ffffffff
        ///&quot;LogFlush&quot;=dword:00000001
        ///&quot;SSHLogOmitPasswords&quot;=dword:00000001
        ///&quot;SSHLogOmitData&quot;=dword:00000000
        ///&quot;Protocol&quot;=&quot;telnet&quot;
        ///&quot;PortNumber&quot;=dword:0000124a
        ///&quot;CloseOnExit&quot;=dword:00000001
        ///&quot;WarnOnClose&quot;=dword:00000001
        ///&quot;PingInterval&quot;=dword:00000005
        ///&quot;PingIntervalSecs&quot;=dword:0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string STARSTG {
            get {
                return ResourceManager.GetString("STARSTG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CURRENT_USER\Software\SimonTatham\PuTTY\Sessions\STARTST]
        ///&quot;Present&quot;=dword:00000001
        ///&quot;HostName&quot;=&quot;jdadevapp06.genco.com&quot;
        ///&quot;LogFileName&quot;=&quot;putty.log&quot;
        ///&quot;LogType&quot;=dword:00000000
        ///&quot;LogFileClash&quot;=dword:ffffffff
        ///&quot;LogFlush&quot;=dword:00000001
        ///&quot;SSHLogOmitPasswords&quot;=dword:00000001
        ///&quot;SSHLogOmitData&quot;=dword:00000000
        ///&quot;Protocol&quot;=&quot;telnet&quot;
        ///&quot;PortNumber&quot;=dword:0000122c
        ///&quot;CloseOnExit&quot;=dword:00000001
        ///&quot;WarnOnClose&quot;=dword:00000001
        ///&quot;PingInterval&quot;=dword:00000005
        ///&quot;PingIntervalSecs&quot;=dwo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string STARTST {
            get {
                return ResourceManager.GetString("STARTST", resourceCulture);
            }
        }
    }
}
